### PR TITLE
fix stagex source url interpolation

### LINKED ISSUE #44: Stagex sync broke due to new url interpolation variable
The error:

```
[2025-04-15T23:55:51Z INFO  what_the_src::sync::stagex] Found stagex package.toml: "stagex/packages/core/cmake/package.toml"
Error: StagexUndefinedVariable("version_major_minor")
```

The culprit:
https://codeberg.org/stagex/stagex/src/branch/main/packages/core/cmake/package.toml#L10

```
mirrors = [ "https://cmake.org/files/v{version_major_minor}/{file}",]
```

The criminal \o/

I'm currently working on a fix.

### PR DESCRIPTION
**Pull request by antonleviathan**
Closes https://github.com/kpcyrd/what-the-src/issues/44

### CODE REVIEW

**Comment by antonleviathan** [comment]
I did a manual spot check for the new interpolation method urls to make sure they're ok.

File: src/sync/stagex.rs [hunk 1]
```diff
@@ -58,6 +58,19 @@ impl Manifest {
...
                     version.replace('.', "_")
                 }
+                "version_major" => {
+                    let version = self.version(source)?;
+                    version.split('.').next().unwrap_or("").to_string()
+                }
+                "version_major_minor" => {
+                    let version = self.version(source)?;
+                    let parts: Vec<&str> = version.split('.').collect();
+                    format!("{}.{}", parts[0], parts[1])
```
Comment (kpcyrd) [inline src/sync/stagex.rs]: Thanks for working on this! This line could panic the process if the version string is a single number with no dots.

I think in that case it could either use the single number as version string, or return an error (you can extend the enum in `src/errors.rs`, there are already some StageX specific errors defined).

File: src/sync/stagex.rs [hunk 2]
```diff
@@ -58,6 +58,19 @@ impl Manifest {
...
+                }
+                "version_strip_suffix" => {
+                    let version = self.version(source)?;
+                    version.splitn(2, '-').next().unwrap_or(&version).to_string()
```
Comment (kpcyrd) [inline src/sync/stagex.rs]: Since it's explicitly the suffix, we may have to split from the back here:
```rust
version.rsplit_once('-').map(|(x, _)| x).unwrap_or(&version)
```

File: src/sync/stagex.rs (hunk 1 above)
Comment (antonleviathan) [reply src/sync/stagex.rs]: No problem, I'll make the adjustment.

File: src/sync/stagex.rs (hunk 2 above)
Comment (antonleviathan) [reply src/sync/stagex.rs]: Derp, definitely.

**Comment by kpcyrd** [comment]
Thanks!
